language: java
jdk:
 - oraclejdk8
 
 cache:
  directories: # keep in sync with CACHED_DIRECTORIES below
  - $HOME/.m2/repository
 
before_install:
 - cp .travis.maven.settings.xml $HOME/.m2/settings.xml
