language: java
jdk:
 - oraclejdk11
 
cache:
  directories: # keep in sync with CACHED_DIRECTORIES below
  - $HOME/.m2/repository
 
before_install:
 - cp .travis.maven.settings.xml $HOME/.m2/settings.xml
 
script:
  - mvn -PTravisNB100 clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn -PTravisNB100 nbm:autoupdate wagon:upload ; fi'
  - mvn -PTravisNB100 test -B

addons:
  ssh_known_hosts:
  - server.arsi.sk
